name: Sync Code

on:
  release:
    types: [published]
  push:
    branches:
      - main
#      - dev

jobs:
  sync_code:
    runs-on: ubuntu-18.04

    steps:
#     - name: Clone repo
#       env:
#         DEBIAN_FRONTEND: noninteractive
#       run: |
#         ls
#         # Have to use clear text as github secrets is disabled by policy
#         git clone  https://50eea2a056bf8ae900cfeebe0d7a341fe5967a88@github.com/Alex-Luo-Jia-Rong/test_hooks.git

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set Codeclimate
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        curl -L https://github.com/codeclimate/codeclimate/archive/master.tar.gz | tar xvz
        cd codeclimate-* && sudo make install
        cd ../
        echo 'version: "1"
        plugins:
           bandit:
             enabled: true
           duplication:
             enabled: true
           pep8:
             enabled: true
           phan:
             enabled: true' > .codeclimate.yml
        codeclimate engines:install
        codeclimate validate-config
        rm -rf codeclimate-*
        codeclimate analyze -f html > result.html
        # python3 send_email.py
    - name: out
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: result.html
